### ISSUE TITLE
The pmenu closes when typing characters

### ISSUE THREAD

**Issue by KabbAmine** [machakann/vim-Verdin#5]
When I manually trigger the omni completion, the popup menu is closed after typing a character.

Here is a demo:

![demo](https://user-images.githubusercontent.com/5658084/36917424-dac6ef2c-1e67-11e8-8c10-187740664fc2.gif)

It occurs only when having `g:Verdin#autocomplete = 0`.

**Comment by machakann** [comment]
Thanks, it is now fixed probably. Please test the latest.

**Comment by KabbAmine** [comment]
Quick and efficient :+1:
Thanks.
